### ISSUE TITLE
Error: Can't get source map for current document

### ISSUE THREAD

**Issue by MartinHignett** [vladimir-kotikov/vscode-sourcemaps-navigator#5]
I can install the extension, but when I try to run it with `Shift + F7`, I get the following error:

> Can't get source map for current document: Cannot create property 'reason' on string 'Can't fetch url from current document at /path/to/myproject/myfile.ts'

**Comment by tsheaff** [comment]
I get the same thing.

**Comment by richard-lopes-ifood** [comment]
Me too

**Comment by andersnm** [comment]
Hey, I ran into this too and went ahead and remixed @vladimir-kotikov 's code into a new similar extension with a bunch of fixes and enhancements

https://marketplace.visualstudio.com/items?itemName=andersnm.sourcemap-helper

(apologies for the spam in this ancient issue and thanks for the starting point and inspiration)

**Comment by vladimir-kotikov** [comment]
Thanks for taking this over! I actually stopped doing web development quite a long time ago and wasn't using the extension and hence had no motivation to work on it, so I'm happy to see it's not got lost and can be reused by someone else. Hope your extension will receive more attention and love!
